name: Saham Scanner IHSG

on:
  schedule:
    # Berjalan Senin-Jumat jam 08:45 UTC (15:45 WIB)
    - cron: '40 16 * * 1-5'
    # Waktu ini pas untuk screening sebelum market tutup (16:00 WIB)
    - cron: '45 8 * * 1-5'
  workflow_dispatch: # Memungkinkan Anda menjalankan manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy requests

      - name: Run Stock Scanner
        env:
          # GitHub akan mengambil nilai ini dari menu Settings > Secrets
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner.py
